auth0:
  audience: https://auth0-aclue-api.com
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kristoffer-schaaf-aclue.us.auth0.com/
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true


